* simple-gl

** About
This is a high level library for using OpenGL.

** Overview

   This is a minimalist, modern OpenGL library based on GLFW.  It provides a framework for working
   with shaders, buffers, textures, and user input.  The goal is to be a "playground" for OpenGL
   development and make it easy to prototype OpenGL code.

   The smallest possible example, showing how to create a window with two instanced triangles (ESC to exit):
   #+begin_src lisp
     (ql:quickload :simple-gl)
     (sgl:display-in (make-instance 'sgl:instanced-opengl-object) (make-instance 'sgl:viewer))
   #+end_src

   To create more complicated graphics, create a subclass of `opengl-object`, or `instanced-opengl-object` and overload the 'initialize-buffers' method.

   (defmethod handle-key ((object opengl-object) window key scancode action mod-keys)
   (defmethod handle-resize ((object opengl-object) window width height)
   (defmethod handle-click ((object opengl-object) window click-info)
   (defmethod handle-scroll ((object opengl-object) window cpos x-scroll y-scroll)
   (defmethod handle-3d-mouse-event ((object opengl-object) (event sn:motion-event))
   
   (defmethod initialize-uniforms ((object opengl-object) &key)
   (defmethod initialize-buffers ((object instanced-opengl-object) &key)
   (defmethod cleanup ((object opengl-object))



** License
ISC


Copyright (c) 2021 Jeremiah LaRocco <jeremiah_larocco@fastmail.com>




* Plan
** TODO Fill in a TODO list.
